export function createMarkdown(article: any, post: string, style: string) {
  return `
# ${article.title}

**Author:** ${article.author}

**Style:** ${style}

**Image:**  
${article.image}

---

## LinkedIn Post

${post}

---

Generated by AI Post Generator
`;
}
