"""create generated posts table

Revision ID: 77e47d28f85a
Revises: 634a614b47d5
Create Date: 2026-06-28 00:09:35.216909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e47d28f85a'
down_revision: Union[str, Sequence[str], None] = '634a614b47d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('article_title', sa.String(length=300), nullable=False),
    sa.Column('article_url', sa.Text(), nullable=False),
    sa.Column('article_author', sa.String(length=255), nullable=True),
    sa.Column('article_image', sa.Text(), nullable=True),
    sa.Column('article_excerpt', sa.Text(), nullable=True),
    sa.Column('generated_post', sa.Text(), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_posts_user_id'), 'generated_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_posts_user_id'), table_name='generated_posts')
    op.drop_table('generated_posts')
    # ### end Alembic commands ###
